module.exports = {
	plugins: ["stylelint-order"],
	rules: {
		"order/order": [
			"custom-properties",
			"dollar-variables",
			"at-variables",
			"custom-properties",
			"less-mixins",
			"declarations",
			"at-rules",
			"rules"
		],
		"order/properties-order": [
			{
				groupName: "definitions",
				emptyLineBefore: "always",
				properties: ["@charset", "@font-face", "@import", "@keyframes", "@media"]
			},
			{
				groupName: "layout",
				emptyLineBefore: "always",
				properties: ["bottom", "left", "position", "right", "top", "z-index"]
			},
			{
				groupName: "box",
				emptyLineBefore: "always",
				properties: [
					"align-content",
					"align-items",
					"align-items",
					"align-self",
					"box-sizing",
					"caption-side",
					"clear",
					"column-count",
					"column-fill",
					"column-gap",
					"column-rule-color",
					"column-rule-style",
					"column-rule-width",
					"column-rule",
					"column-span",
					"column-width",
					"columns",
					"display",
					"empty-cells",
					"flex-basis",
					"flex-direction",
					"flex-flow",
					"flex-grow",
					"flex-shrink",
					"flex-wrap",
					"flex",
					"float",
					"grid-area",
					"grid-auto-columns",
					"grid-auto-flow",
					"grid-auto-rows",
					"grid-column-end",
					"grid-column-gap",
					"grid-column-start",
					"grid-column",
					"grid-gap",
					"grid-row-end",
					"grid-row-gap",
					"grid-row-start",
					"grid-row",
					"grid-template-areas",
					"grid-template-columns",
					"grid-template-rows",
					"grid-template",
					"grid",
					"height",
					"justify-content",
					"margin-bottom",
					"margin-left",
					"margin-right",
					"margin-top",
					"margin",
					"max-height",
					"max-width",
					"min-height",
					"min-width",
					"object-fit",
					"object-position",
					"opacity",
					"order",
					"overflow-x",
					"overflow-y",
					"overflow",
					"padding-bottom",
					"padding-left",
					"padding-right",
					"padding-top",
					"padding",
					"page-break-after",
					"page-break-before",
					"page-break-inside",
					"table-layout",
					"width"
				]
			},
			{
				groupName: "visual",
				emptyLineBefore: "always",
				properties: [
					"animation-delay",
					"animation-direction",
					"animation-duration",
					"animation-fill-mode",
					"animation-iteration-count",
					"animation-name",
					"animation-play-state",
					"animation-timing-function",
					"animation",
					"backface-visibility",
					"background-attachment",
					"background-blend-mode",
					"background-clip",
					"background-color",
					"background-image",
					"background-origin",
					"background-position",
					"background-repeat",
					"background-size",
					"background",
					"border-bottom-color",
					"border-bottom-left-radius",
					"border-bottom-right-radius",
					"border-bottom-style",
					"border-bottom-width",
					"border-bottom",
					"border-collapse",
					"border-color",
					"border-image-outset",
					"border-image-repeat",
					"border-image-slice",
					"border-image-source",
					"border-image-width",
					"border-image",
					"border-left-color",
					"border-left-style",
					"border-left-width",
					"border-left",
					"border-radius",
					"border-right-color",
					"border-right-style",
					"border-right-width",
					"border-right",
					"border-spacing",
					"border-style",
					"border-top-color",
					"border-top-left-radius",
					"border-top-right-radius",
					"border-top-style",
					"border-top-width",
					"border-top",
					"border-width",
					"border",
					"box-decoration-break",
					"box-shadow",
					"caret-color",
					"clip",
					"color",
					"filter",
					"isolation",
					"mix-blend-mode",
					"outline-color",
					"outline-offset",
					"outline-style",
					"outline-width",
					"outline",
					"perspective-origin",
					"perspective",
					"resize",
					"scroll-behavior",
					"transform-origin",
					"transform-style",
					"transform",
					"transition-delay",
					"transition-duration",
					"transition-property",
					"transition-timing-function",
					"transition",
					"user-select",
					"visibility"
				]
			},
			{
				groupName: "type",
				emptyLineBefore: "always",
				properties: [
					"content",
					"counter-increment",
					"counter-reset",
					"cursor",
					"direction",
					"font-family",
					"font-kerning",
					"font-size-adjust",
					"font-size",
					"font-stretch",
					"font-style",
					"font-variant",
					"font-weight",
					"font",
					"hanging-punctuation",
					"hyphens",
					"letter-spacing",
					"line-height",
					"list-style-image",
					"list-style-position",
					"list-style-type",
					"list-style",
					"pointer-events",
					"quotes",
					"tab-size",
					"text-align-last",
					"text-align",
					"text-decoration-color",
					"text-decoration-line",
					"text-decoration-style",
					"text-decoration",
					"text-indent",
					"text-justify",
					"text-overflow",
					"text-shadow",
					"text-transform",
					"unicode-bidi",
					"vertical-align",
					"white-space",
					"word-break",
					"word-spacing",
					"word-wrap",
					"writing-mode"
				]
			}
		],
		"order/properties-alphabetical-order": true
	},
	rules: {
		"at-rule-name-case": "lower",
		"at-rule-name-space-after": "always",
		"at-rule-no-unknown": true,
		"at-rule-no-vendor-prefix": true,
		"at-rule-semicolon-newline-after": "always",
		"block-closing-brace-empty-line-before": "never",
		"block-closing-brace-newline-after": "always-multi-line",
		"block-closing-brace-newline-before": "always-multi-line",
		"block-no-empty": true,
		"block-opening-brace-newline-after": "always-multi-line",
		"block-opening-brace-space-after": "always-single-line",
		"block-opening-brace-space-before": "always",
		"color-hex-case": "lower",
		"color-hex-length": "short",
		"color-named": "always-where-possible",
		"color-no-invalid-hex": true,
		"comment-empty-line-before": "always",
		"comment-no-empty": true,
		"comment-whitespace-inside": "always",
		"comment-word-blacklist": [],
		"custom-media-pattern": "",
		"custom-property-pattern": "",
		"declaration-bang-space-after": "never",
		"declaration-bang-space-before": "always",
		"declaration-block-no-duplicate-properties": true,
		"declaration-block-no-redundant-longhand-properties": true,
		"declaration-block-no-shorthand-property-overrides": true,
		"declaration-block-semicolon-newline-after": "always-multi-line",
		"declaration-block-semicolon-newline-before": "never-multi-line",
		"declaration-block-semicolon-space-after": "always-single-line",
		"declaration-block-semicolon-space-before": "never",
		"declaration-block-single-line-max-declarations": 1,
		"declaration-block-trailing-semicolon": "always",
		"declaration-colon-space-after": "always-single-line",
		"declaration-colon-space-before": "never",
		"declaration-property-unit-blacklist": {},
		"declaration-property-unit-whitelist": {},
		"declaration-property-value-blacklist": {},
		"declaration-property-value-whitelist": {},
		"font-family-name-quotes": "always-unless-keyword",
		"font-family-no-duplicate-names": true,
		"font-weight-notation": "numeric",
		"function-blacklist": "string",
		"function-calc-no-unspaced-operator": true,
		"function-comma-space-after": "always",
		"function-comma-space-before": "never",
		"function-linear-gradient-no-nonstandard-direction": true,
		"function-max-empty-lines": 0,
		"function-name-case": "lower",
		"function-parentheses-space-inside": "never",
		"function-url-no-scheme-relative": true,
		"function-url-quotes": "always",
		indentation: "tab",
		"keyframe-declaration-no-important": true,
		"length-zero-no-unit": true,
		"max-empty-lines": 1,
		"max-line-length": 120,
		"max-nesting-depth": 5,
		"media-feature-colon-space-after": "always",
		"media-feature-colon-space-before": "never",
		"media-feature-name-blacklist": "",
		"media-feature-name-case": "lower",
		"media-feature-name-no-unknown": true,
		"media-feature-name-no-vendor-prefix": true,
		"media-feature-parentheses-space-inside": "never",
		"media-feature-range-operator-space-after": "always",
		"media-feature-range-operator-space-before": "always",
		"media-query-list-comma-newline-after": "always",
		"media-query-list-comma-newline-before": "always",
		"media-query-list-comma-space-after": "always",
		"media-query-list-comma-space-before": "always",
		"no-duplicate-selectors": true,
		"no-empty-source": true,
		"no-eol-whitespace": true,
		"no-extra-semicolons": true,
		"no-invalid-double-slash-comments": true,
		"no-missing-end-of-source-newline": true,
		"no-unknown-animations": true,
		"number-leading-zero": "never",
		"number-max-precision": 5,
		"number-no-trailing-zeros": true,
		"property-blacklist": "",
		"property-case": "lower",
		"property-no-unknown": true,
		"selector-attribute-brackets-space-inside": "never",
		"selector-attribute-operator-blacklist": "",
		"selector-attribute-operator-space-after": "never",
		"selector-attribute-operator-space-before": "never",
		"selector-attribute-quotes": "always",
		"selector-class-pattern": "",
		"selector-combinator-space-after": "always",
		"selector-combinator-space-before": "always",
		"selector-descendant-combinator-no-non-space": true,
		"selector-id-pattern": "",
		"selector-list-comma-newline-after": "always",
		"selector-list-comma-space-before": "always-single-line",
		"selector-max-compound-selectors": 6,
		"selector-max-empty-lines": 0,
		"selector-max-specificity": "0,7,0",
		"selector-nested-pattern": "",
		"selector-no-vendor-prefix": true,
		"selector-pseudo-class-blacklist": "",
		"selector-pseudo-class-case": "lower",
		"selector-pseudo-class-no-unknown": true,
		"selector-pseudo-class-parentheses-space-inside": "never",
		"selector-pseudo-element-case": "lower",
		"selector-pseudo-element-colon-notation": "single",
		"selector-pseudo-element-no-unknown": true,
		"selector-type-case": "lower",
		"shorthand-property-no-redundant-values": true,
		"string-no-newline": true,
		"string-quotes": "double",
		"unit-blacklist": "",
		"unit-case": "lower",
		"unit-no-unknown": true,
		"value-keyword-case": "lower",
		"value-list-comma-newline-after": "always-multi-line",
		"value-list-comma-space-after": "always-single-line",
		"value-list-comma-space-before": "never",
		"value-list-max-empty-lines": 0,
		"value-no-vendor-prefix": true
	}
}
